<!DOCTYPE html>
<html lang="en">
<head>
	<link href= "styles/style.css" rel="stylesheet"/>
	<meta charset="utf-8" />
	<meta name="description" content="Assignment1" />
	<meta name="keywords" content="HTML5" />
	<meta name="author" content="Ramanaidu sureddy"  />
    <title>vacancies</title>
	<script type="text/javascript" src="Scripts/apply.js">
	
    </script>

</head>
<body >

	<header><img src="images/RANA.gif" alt="RanaTech" width="200" height="100" ></header>
	<h1><em>RanaTech</em></h1>
	<nav>

      <a href="index.html">HOME</a>
	<a href="jobs.html">JOBS</a>
	<a href="apply.html">APPLY</a>
	<a href="about.html">ABOUT</a>
    <a href="enhancements.html">ENHANCEMENTS</a>
  </nav>